#docker-compose.yml
version: '3.5'

# Для сборки - docker-compose build
# Для запуска сценария - docker-compose up
# Для запуска отдельных сервисов - docker-compose run <service_name>

services:
    # 1 контейнер === 1 сервис
    shippyserver:
        # Ребут контейнера каждый раз в случае конфликтов/ошибок/беды
        restart: always
        # Путь до Dockerfile сервиса
        build: ./shippyserver
        depends_on: 
            - database
            - shippyvessel
        ports:
            - 50051:50051
        environment:
            MICRO_SERVER_ADDRESS: ":50051"
            DB_HOST: "mongodb://database:27017"

    shippyvessel:
        restart: always 
        build: ./shippyvessel 
        ports:
            - 50054:50051
        environment: 
            MICRO_SERVER_ADDRESS: ":50051"
            DB_HOST: "mongodb://database:27017"

    shippyclient:
        build: ./shippyclient 
        ports:
            - 50052:50051 
        environment: 
            MICRO_SERVER_ADDRESS: ":50051"

    user:
        build: ./userserver
        ports:
            - 50055:50051
        environment: 
            MICRO_SERVER_ADDRESS: ":50051"



    database:
        image: mongo
        container_name: "database"
        environment: 
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017
        command: mongod --logpath=/dev/null

    datastore:
        image: postgres:alpine 
        environment:
            POSTGRES_PASSWORD: "?"
            POSTGRES_USER: "admin"
        ports:
            - 5432:5432 




