#docker-compose.yml
version: '3.5'

# Для сборки - docker-compose build
# Для запуска сценария - docker-compose up
# Для запуска отдельных сервисов - docker-compose run <service_name>

services:

        # 1 контейнер === 1 сервис
    shippyserver:
        # Ребут контейнера каждый раз в случае конфликтов/ошибок/беды
        restart: always
        # Путь до Dockerfile сервиса
        build: ./shippyserver
        depends_on: 
            - datastore
            - shippyvessel
        ports:
            - 50051:50051
        environment:
            MICRO_SERVER_ADDRESS: ":50051"
            DB_HOST: "mongodb://database:27017"

    shippyvessel:
        restart: always 
        build: ./shippyvessel 
        ports:
            - 50054:50051
        environment: 
            MICRO_SERVER_ADDRESS: ":50051"
            DB_HOST: "mongodb://database:27017"

    shippyclient:
        build: ./shippyclient 
        ports:
            - 50052:50051 
        environment: 
            MICRO_SERVER_ADDRESS: ":50051"

    datastore:
        image: mongo
        container_name: "datastore"
        environment: 
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017
        command: mongod --logpath=/dev/null



    userserver:
        restart: always
        build: ./userserver
        ports:
            - 50055:50051
        environment:
            MICRO_ADDRESS: ":50051"
            DB_HOST: "database"
            DB_USER: "admin"
            DB_PASSWORD: "password"
            DB_NAME: "postgres"

    usercli:
        build: ./usercli



    database:
        image: postgres:alpine
        environment:
            POSTGRES_PASSWORD: "password"
            POSTGRES_USER: "admin"
        ports:
        - 5431:5432



