#docker-compose.yml
version: '3.5'

# Для сборки - docker-compose build
# Для запуска сценария - docker-compose up
# Для запуска отдельных сервисов - docker-compose run <service_name>

services:
    # 1 контейнер === 1 сервис
    shippyserver:
        # Ребут контейнера каждый раз в случае конфликтов/ошибок/беды
        restart: always
        # Путь до Dockerfile сервиса
        build: ./shippyserver
        depends_on: 
            - shippyvessel
        ports:
            - 50051:50051
        environment:
            MICRO_SERVER_ADDRESS: ":50051"

    shippyvessel:
        restart: always 
        build: ./shippyvessel 
        ports:
            - 50054:50051
        environment: 
            MICRO_SERVER_ADDRESS: ":50051"

    shippyclient:
        build: ./shippyclient 
        ports:
            - 50052:50051 
        environment: 
            MICRO_SERVER_ADDRESS: ":50051"
            




