// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/consignment/consignment.proto

package consignment

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response_Things int32

const (
	Response_FIRST  Response_Things = 0
	Response_SECOND Response_Things = 1
	Response_THIRD  Response_Things = 3
	Response_FOURTH Response_Things = 4
)

var Response_Things_name = map[int32]string{
	0: "FIRST",
	1: "SECOND",
	3: "THIRD",
	4: "FOURTH",
}

var Response_Things_value = map[string]int32{
	"FIRST":  0,
	"SECOND": 1,
	"THIRD":  3,
	"FOURTH": 4,
}

func (x Response_Things) String() string {
	return proto.EnumName(Response_Things_name, int32(x))
}

func (Response_Things) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{1, 0}
}

//Обозначение именованного набора полей
type Request struct {
	//тип имя = номер поля;
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Salary               int64    `protobuf:"varint,3,opt,name=salary,proto3" json:"salary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Request) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Request) GetSalary() int64 {
	if m != nil {
		return m.Salary
	}
	return 0
}

type Response struct {
	MyDouble             float64         `protobuf:"fixed64,1,opt,name=my_double,json=myDouble,proto3" json:"my_double,omitempty"`
	MyFloat              float32         `protobuf:"fixed32,2,opt,name=my_float,json=myFloat,proto3" json:"my_float,omitempty"`
	MyUint32             uint32          `protobuf:"varint,3,opt,name=my_uint32,json=myUint32,proto3" json:"my_uint32,omitempty"`
	MyUint64             uint64          `protobuf:"varint,4,opt,name=my_uint64,json=myUint64,proto3" json:"my_uint64,omitempty"`
	MyFixed32            uint32          `protobuf:"fixed32,5,opt,name=my_fixed32,json=myFixed32,proto3" json:"my_fixed32,omitempty"`
	MyBool               bool            `protobuf:"varint,6,opt,name=my_bool,json=myBool,proto3" json:"my_bool,omitempty"`
	MyString             string          `protobuf:"bytes,7,opt,name=my_string,json=myString,proto3" json:"my_string,omitempty"`
	MyBytes              []byte          `protobuf:"bytes,8,opt,name=my_bytes,json=myBytes,proto3" json:"my_bytes,omitempty"`
	Things               Response_Things `protobuf:"varint,9,opt,name=things,proto3,enum=consignment.Response_Things" json:"things,omitempty"`
	Req                  *Request        `protobuf:"bytes,10,opt,name=req,proto3" json:"req,omitempty"`
	Snippet              []*Request      `protobuf:"bytes,11,rep,name=snippet,proto3" json:"snippet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMyDouble() float64 {
	if m != nil {
		return m.MyDouble
	}
	return 0
}

func (m *Response) GetMyFloat() float32 {
	if m != nil {
		return m.MyFloat
	}
	return 0
}

func (m *Response) GetMyUint32() uint32 {
	if m != nil {
		return m.MyUint32
	}
	return 0
}

func (m *Response) GetMyUint64() uint64 {
	if m != nil {
		return m.MyUint64
	}
	return 0
}

func (m *Response) GetMyFixed32() uint32 {
	if m != nil {
		return m.MyFixed32
	}
	return 0
}

func (m *Response) GetMyBool() bool {
	if m != nil {
		return m.MyBool
	}
	return false
}

func (m *Response) GetMyString() string {
	if m != nil {
		return m.MyString
	}
	return ""
}

func (m *Response) GetMyBytes() []byte {
	if m != nil {
		return m.MyBytes
	}
	return nil
}

func (m *Response) GetThings() Response_Things {
	if m != nil {
		return m.Things
	}
	return Response_FIRST
}

func (m *Response) GetReq() *Request {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *Response) GetSnippet() []*Request {
	if m != nil {
		return m.Snippet
	}
	return nil
}

type OuterSearcher struct {
	Result               []*OuterSearcher_InnerSearcher `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *OuterSearcher) Reset()         { *m = OuterSearcher{} }
func (m *OuterSearcher) String() string { return proto.CompactTextString(m) }
func (*OuterSearcher) ProtoMessage()    {}
func (*OuterSearcher) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{2}
}

func (m *OuterSearcher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OuterSearcher.Unmarshal(m, b)
}
func (m *OuterSearcher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OuterSearcher.Marshal(b, m, deterministic)
}
func (m *OuterSearcher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OuterSearcher.Merge(m, src)
}
func (m *OuterSearcher) XXX_Size() int {
	return xxx_messageInfo_OuterSearcher.Size(m)
}
func (m *OuterSearcher) XXX_DiscardUnknown() {
	xxx_messageInfo_OuterSearcher.DiscardUnknown(m)
}

var xxx_messageInfo_OuterSearcher proto.InternalMessageInfo

func (m *OuterSearcher) GetResult() []*OuterSearcher_InnerSearcher {
	if m != nil {
		return m.Result
	}
	return nil
}

type OuterSearcher_InnerSearcher struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OuterSearcher_InnerSearcher) Reset()         { *m = OuterSearcher_InnerSearcher{} }
func (m *OuterSearcher_InnerSearcher) String() string { return proto.CompactTextString(m) }
func (*OuterSearcher_InnerSearcher) ProtoMessage()    {}
func (*OuterSearcher_InnerSearcher) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{2, 0}
}

func (m *OuterSearcher_InnerSearcher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OuterSearcher_InnerSearcher.Unmarshal(m, b)
}
func (m *OuterSearcher_InnerSearcher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OuterSearcher_InnerSearcher.Marshal(b, m, deterministic)
}
func (m *OuterSearcher_InnerSearcher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OuterSearcher_InnerSearcher.Merge(m, src)
}
func (m *OuterSearcher_InnerSearcher) XXX_Size() int {
	return xxx_messageInfo_OuterSearcher_InnerSearcher.Size(m)
}
func (m *OuterSearcher_InnerSearcher) XXX_DiscardUnknown() {
	xxx_messageInfo_OuterSearcher_InnerSearcher.DiscardUnknown(m)
}

var xxx_messageInfo_OuterSearcher_InnerSearcher proto.InternalMessageInfo

func (m *OuterSearcher_InnerSearcher) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *OuterSearcher_InnerSearcher) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type AnotherSeacher struct {
	Result               *OuterSearcher_InnerSearcher `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *AnotherSeacher) Reset()         { *m = AnotherSeacher{} }
func (m *AnotherSeacher) String() string { return proto.CompactTextString(m) }
func (*AnotherSeacher) ProtoMessage()    {}
func (*AnotherSeacher) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{3}
}

func (m *AnotherSeacher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnotherSeacher.Unmarshal(m, b)
}
func (m *AnotherSeacher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnotherSeacher.Marshal(b, m, deterministic)
}
func (m *AnotherSeacher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnotherSeacher.Merge(m, src)
}
func (m *AnotherSeacher) XXX_Size() int {
	return xxx_messageInfo_AnotherSeacher.Size(m)
}
func (m *AnotherSeacher) XXX_DiscardUnknown() {
	xxx_messageInfo_AnotherSeacher.DiscardUnknown(m)
}

var xxx_messageInfo_AnotherSeacher proto.InternalMessageInfo

func (m *AnotherSeacher) GetResult() *OuterSearcher_InnerSearcher {
	if m != nil {
		return m.Result
	}
	return nil
}

type TimeDate struct {
	Year                 int32    `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month                int32    `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day                  int32    `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	Hour                 int32    `protobuf:"varint,4,opt,name=hour,proto3" json:"hour,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeDate) Reset()         { *m = TimeDate{} }
func (m *TimeDate) String() string { return proto.CompactTextString(m) }
func (*TimeDate) ProtoMessage()    {}
func (*TimeDate) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{4}
}

func (m *TimeDate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeDate.Unmarshal(m, b)
}
func (m *TimeDate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeDate.Marshal(b, m, deterministic)
}
func (m *TimeDate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeDate.Merge(m, src)
}
func (m *TimeDate) XXX_Size() int {
	return xxx_messageInfo_TimeDate.Size(m)
}
func (m *TimeDate) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeDate.DiscardUnknown(m)
}

var xxx_messageInfo_TimeDate proto.InternalMessageInfo

func (m *TimeDate) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *TimeDate) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *TimeDate) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *TimeDate) GetHour() int32 {
	if m != nil {
		return m.Hour
	}
	return 0
}

func init() {
	proto.RegisterEnum("consignment.Response_Things", Response_Things_name, Response_Things_value)
	proto.RegisterType((*Request)(nil), "consignment.Request")
	proto.RegisterType((*Response)(nil), "consignment.Response")
	proto.RegisterType((*OuterSearcher)(nil), "consignment.OuterSearcher")
	proto.RegisterType((*OuterSearcher_InnerSearcher)(nil), "consignment.OuterSearcher.InnerSearcher")
	proto.RegisterType((*AnotherSeacher)(nil), "consignment.AnotherSeacher")
	proto.RegisterType((*TimeDate)(nil), "consignment.TimeDate")
}

func init() {
	proto.RegisterFile("proto/consignment/consignment.proto", fileDescriptor_e5e5ab05dfa973d5)
}

var fileDescriptor_e5e5ab05dfa973d5 = []byte{
	// 564 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x54, 0x51, 0x8f, 0xd2, 0x4c,
	0x14, 0xa5, 0x5b, 0x68, 0xcb, 0xe5, 0x63, 0x43, 0x26, 0xfb, 0x69, 0x45, 0x4d, 0x36, 0x35, 0x31,
	0xfb, 0x84, 0x09, 0x8b, 0x44, 0x1f, 0x4c, 0x74, 0x97, 0x65, 0xe1, 0x45, 0xcc, 0xb4, 0xfb, 0xe2,
	0x0b, 0x29, 0x30, 0x42, 0x93, 0xb6, 0xc3, 0x4e, 0xa7, 0xc6, 0xfe, 0x03, 0x7f, 0x8f, 0xff, 0xc0,
	0x7f, 0xe6, 0x9d, 0xa1, 0x8d, 0xa0, 0xf8, 0xa0, 0x6f, 0xe7, 0xdc, 0x73, 0xce, 0x9d, 0x3b, 0x9d,
	0x9b, 0xc2, 0xb3, 0xad, 0xe0, 0x92, 0xbf, 0x58, 0xf2, 0x34, 0x8b, 0xd6, 0x69, 0xc2, 0x52, 0xb9,
	0x8f, 0x7b, 0x5a, 0x25, 0xad, 0xbd, 0x92, 0x77, 0x0b, 0x36, 0x65, 0xf7, 0x39, 0xcb, 0x24, 0x21,
	0x50, 0x5f, 0xf0, 0x55, 0xe1, 0x1a, 0xe7, 0xc6, 0x45, 0x93, 0x6a, 0x4c, 0x3a, 0x60, 0x86, 0x6b,
	0xe6, 0x9e, 0x60, 0xa9, 0x41, 0x15, 0x24, 0x0f, 0xc0, 0xca, 0xc2, 0x38, 0x14, 0x85, 0x6b, 0x62,
	0xd1, 0xa4, 0x25, 0xf3, 0xbe, 0x99, 0xe0, 0x50, 0x96, 0x6d, 0xb1, 0x37, 0x23, 0x8f, 0xa1, 0x99,
	0x14, 0xf3, 0x15, 0xcf, 0x17, 0x31, 0xd3, 0xfd, 0x0c, 0xea, 0x24, 0xc5, 0x48, 0x73, 0xf2, 0x08,
	0x10, 0xcf, 0x3f, 0xc5, 0x3c, 0x94, 0xba, 0xf1, 0x09, 0xb5, 0x93, 0x62, 0xac, 0x68, 0x99, 0xcb,
	0xa3, 0x54, 0x5e, 0xf6, 0x75, 0xff, 0xb6, 0xca, 0xdd, 0x69, 0xbe, 0x27, 0x0e, 0x07, 0x6e, 0x1d,
	0xc5, 0x7a, 0x25, 0x0e, 0x07, 0xe4, 0x29, 0x80, 0x6a, 0x1a, 0x7d, 0x61, 0x2b, 0x8c, 0x36, 0x50,
	0xb5, 0x29, 0xda, 0xc7, 0xbb, 0x02, 0x79, 0x08, 0x78, 0xc6, 0x7c, 0xc1, 0x79, 0xec, 0x5a, 0xa8,
	0x39, 0xd4, 0x4a, 0x8a, 0x2b, 0x64, 0x65, 0xd3, 0x4c, 0x8a, 0x28, 0x5d, 0xbb, 0xb6, 0xbe, 0x39,
	0x36, 0xf5, 0x35, 0x2f, 0x27, 0x5d, 0x14, 0x92, 0x65, 0xae, 0x83, 0xda, 0x7f, 0x6a, 0xd2, 0x2b,
	0x45, 0xc9, 0x00, 0x2c, 0xb9, 0x41, 0x4f, 0xe6, 0x36, 0x51, 0x38, 0xed, 0x3f, 0xe9, 0xed, 0x7f,
	0xe8, 0xea, 0x43, 0xf4, 0x02, 0xed, 0xa1, 0xa5, 0x97, 0x3c, 0x07, 0x53, 0xb0, 0x7b, 0x17, 0x30,
	0xd2, 0xea, 0x9f, 0xfd, 0x12, 0xd1, 0xaf, 0x40, 0x95, 0x81, 0xf4, 0xc0, 0xce, 0xd2, 0x68, 0xbb,
	0x65, 0xd2, 0x6d, 0x9d, 0x9b, 0x7f, 0xf4, 0x56, 0x26, 0x6f, 0x08, 0xd6, 0xee, 0x24, 0xd2, 0x84,
	0xc6, 0x78, 0x4a, 0xfd, 0xa0, 0x53, 0x23, 0x00, 0x96, 0x7f, 0x73, 0x3d, 0x7b, 0x3f, 0xea, 0x18,
	0xaa, 0x1c, 0x4c, 0xa6, 0x74, 0xd4, 0x31, 0x55, 0x79, 0x3c, 0xbb, 0xa3, 0xc1, 0xa4, 0x53, 0xf7,
	0xbe, 0x1a, 0xd0, 0x9e, 0xe5, 0x92, 0x09, 0x9f, 0x85, 0x62, 0xb9, 0x61, 0x82, 0xbc, 0x05, 0x4b,
	0xb0, 0x2c, 0x8f, 0x25, 0x3e, 0x9b, 0x3a, 0xf8, 0xe2, 0xe0, 0xe0, 0x03, 0x6f, 0x6f, 0x9a, 0xa6,
	0x3f, 0x19, 0x2d, 0x73, 0xdd, 0x97, 0xd0, 0x3e, 0x10, 0xd4, 0x5e, 0x2d, 0xf9, 0x6a, 0xb7, 0x07,
	0x0d, 0xaa, 0xb1, 0xda, 0xab, 0x5c, 0xc4, 0xfa, 0xf9, 0x9b, 0x54, 0x41, 0x8f, 0xc2, 0xe9, 0xbb,
	0x94, 0xcb, 0x8d, 0x0e, 0xfe, 0x36, 0x8a, 0xf1, 0x2f, 0xa3, 0x78, 0x1f, 0xc1, 0x09, 0xa2, 0x84,
	0x8d, 0x42, 0xc9, 0xd4, 0x14, 0x05, 0xea, 0xd5, 0x14, 0x0a, 0x93, 0x33, 0x68, 0x24, 0x3c, 0x95,
	0x9b, 0x72, 0xbf, 0x77, 0x44, 0xcd, 0xb6, 0x0a, 0x77, 0xeb, 0x8d, 0x3b, 0x8f, 0x50, 0x65, 0x37,
	0x3c, 0x17, 0x7a, 0xe9, 0x30, 0xab, 0x70, 0xff, 0xbb, 0x01, 0xad, 0x00, 0x1f, 0xc1, 0x67, 0xe2,
	0x73, 0xb4, 0x64, 0xe4, 0x15, 0xd8, 0x13, 0x29, 0xb7, 0xb7, 0x37, 0x01, 0x39, 0xfa, 0x58, 0xdd,
	0xff, 0x8f, 0x6e, 0x88, 0x57, 0x23, 0xaf, 0xc1, 0x51, 0xc9, 0x0f, 0x33, 0xff, 0xaf, 0xa3, 0x6f,
	0xa0, 0x75, 0x9d, 0x0b, 0x81, 0x55, 0x75, 0x4f, 0x72, 0xe8, 0xab, 0xae, 0xde, 0x3d, 0x5e, 0xf6,
	0x6a, 0x0b, 0x4b, 0xff, 0x10, 0x2e, 0x7f, 0x04, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x66, 0xca, 0xa9,
	0x37, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestServiceClient interface {
	//Можно передать в качестве аргумента что-то, а можно и ничего
	HttpGET(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	HttpPOST(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	CurrentTime(ctx context.Context, in *TimeDate, opts ...grpc.CallOption) (*TimeDate, error)
}

type testServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestServiceClient(cc grpc.ClientConnInterface) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) HttpGET(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/consignment.TestService/HttpGET", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) HttpPOST(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/consignment.TestService/HttpPOST", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) CurrentTime(ctx context.Context, in *TimeDate, opts ...grpc.CallOption) (*TimeDate, error) {
	out := new(TimeDate)
	err := c.cc.Invoke(ctx, "/consignment.TestService/CurrentTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServiceServer is the server API for TestService service.
type TestServiceServer interface {
	//Можно передать в качестве аргумента что-то, а можно и ничего
	HttpGET(context.Context, *Request) (*Response, error)
	HttpPOST(context.Context, *Request) (*Response, error)
	CurrentTime(context.Context, *TimeDate) (*TimeDate, error)
}

// UnimplementedTestServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTestServiceServer struct {
}

func (*UnimplementedTestServiceServer) HttpGET(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HttpGET not implemented")
}
func (*UnimplementedTestServiceServer) HttpPOST(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HttpPOST not implemented")
}
func (*UnimplementedTestServiceServer) CurrentTime(ctx context.Context, req *TimeDate) (*TimeDate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CurrentTime not implemented")
}

func RegisterTestServiceServer(s *grpc.Server, srv TestServiceServer) {
	s.RegisterService(&_TestService_serviceDesc, srv)
}

func _TestService_HttpGET_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).HttpGET(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consignment.TestService/HttpGET",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).HttpGET(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_HttpPOST_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).HttpPOST(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consignment.TestService/HttpPOST",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).HttpPOST(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_CurrentTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeDate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).CurrentTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consignment.TestService/CurrentTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).CurrentTime(ctx, req.(*TimeDate))
	}
	return interceptor(ctx, in, info, handler)
}

var _TestService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "consignment.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HttpGET",
			Handler:    _TestService_HttpGET_Handler,
		},
		{
			MethodName: "HttpPOST",
			Handler:    _TestService_HttpPOST_Handler,
		},
		{
			MethodName: "CurrentTime",
			Handler:    _TestService_CurrentTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/consignment/consignment.proto",
}
