// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dop/dop.proto

package dop

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//Здесь будут указываться требования для хранения
//товара
type Request struct {
	Capacity             int32    `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,2,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_685e958e23e1f6b8, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Request) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

//Как выглядит ответ (свободные места под хранение товара)
type Response struct {
	Place                *Place   `protobuf:"bytes,1,opt,name=place,proto3" json:"place,omitempty"`
	Places               []*Place `protobuf:"bytes,2,rep,name=places,proto3" json:"places,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_685e958e23e1f6b8, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetPlace() *Place {
	if m != nil {
		return m.Place
	}
	return nil
}

func (m *Response) GetPlaces() []*Place {
	if m != nil {
		return m.Places
	}
	return nil
}

//Как выглядит само место для хранения товара
type Place struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Capacity             int32    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,3,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Available            bool     `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	OwnerId              string   `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Place) Reset()         { *m = Place{} }
func (m *Place) String() string { return proto.CompactTextString(m) }
func (*Place) ProtoMessage()    {}
func (*Place) Descriptor() ([]byte, []int) {
	return fileDescriptor_685e958e23e1f6b8, []int{2}
}

func (m *Place) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Place.Unmarshal(m, b)
}
func (m *Place) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Place.Marshal(b, m, deterministic)
}
func (m *Place) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Place.Merge(m, src)
}
func (m *Place) XXX_Size() int {
	return xxx_messageInfo_Place.Size(m)
}
func (m *Place) XXX_DiscardUnknown() {
	xxx_messageInfo_Place.DiscardUnknown(m)
}

var xxx_messageInfo_Place proto.InternalMessageInfo

func (m *Place) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Place) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Place) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func (m *Place) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Place) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *Place) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "dop.Request")
	proto.RegisterType((*Response)(nil), "dop.Response")
	proto.RegisterType((*Place)(nil), "dop.Place")
}

func init() {
	proto.RegisterFile("proto/dop/dop.proto", fileDescriptor_685e958e23e1f6b8)
}

var fileDescriptor_685e958e23e1f6b8 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x51, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x25, 0x49, 0x93, 0x26, 0x07, 0x65, 0x38, 0x96, 0x50, 0x81, 0x54, 0x79, 0x62, 0x0a, 0x52,
	0x59, 0x59, 0x90, 0x2a, 0x24, 0xb6, 0xca, 0x0c, 0x8c, 0x95, 0x9b, 0x9c, 0xc0, 0x52, 0x1a, 0x9b,
	0xc4, 0xb4, 0xf0, 0x6b, 0xf8, 0xab, 0x38, 0xd7, 0xa8, 0x88, 0x0e, 0x0c, 0x91, 0xde, 0x47, 0xee,
	0xf9, 0xf9, 0x0c, 0x17, 0xb6, 0x35, 0xce, 0xdc, 0x56, 0xc6, 0xf6, 0x5f, 0xc1, 0x0c, 0x23, 0x0f,
	0xc5, 0x02, 0xc6, 0x92, 0xde, 0x3f, 0xa8, 0x73, 0x38, 0x85, 0xb4, 0x54, 0x56, 0x95, 0xda, 0x7d,
	0xe5, 0xc1, 0x2c, 0xb8, 0x89, 0xe5, 0x81, 0xe3, 0x35, 0xc0, 0x46, 0x7d, 0xae, 0x76, 0xa4, 0x5f,
	0xdf, 0x5c, 0x1e, 0xb2, 0x9b, 0x79, 0xe5, 0x85, 0x05, 0xb1, 0x84, 0x54, 0x52, 0x67, 0x4d, 0xd3,
	0x11, 0xce, 0x20, 0xb6, 0xb5, 0x2a, 0x89, 0x33, 0x4e, 0xe7, 0x50, 0xf4, 0x27, 0x2e, 0x7b, 0x45,
	0xee, 0x0d, 0x14, 0x90, 0x30, 0xe8, 0x7c, 0x50, 0x74, 0xf4, 0xcb, 0xe0, 0x88, 0xef, 0x00, 0x62,
	0x56, 0xf0, 0x1c, 0x42, 0x5d, 0x71, 0x58, 0x26, 0x3d, 0xfa, 0x53, 0x33, 0xfc, 0xb7, 0x66, 0x74,
	0x54, 0x13, 0x11, 0x46, 0x8d, 0xda, 0x50, 0x3e, 0xe2, 0x30, 0xc6, 0x78, 0x05, 0x99, 0xda, 0x2a,
	0x5d, 0xab, 0x75, 0x4d, 0x79, 0xec, 0x8d, 0x54, 0xfe, 0x0a, 0x78, 0x09, 0xa9, 0xd9, 0x35, 0xd4,
	0xae, 0x7c, 0x85, 0x84, 0xa7, 0xc6, 0xcc, 0x9f, 0xaa, 0xf9, 0x3d, 0xc0, 0xc2, 0xd8, 0x67, 0x6a,
	0xb7, 0xda, 0xb7, 0x2c, 0x60, 0xf2, 0xa8, 0x9b, 0xea, 0xe1, 0x30, 0x79, 0xc6, 0x97, 0x1a, 0x76,
	0x3b, 0x9d, 0x0c, 0x6c, 0xbf, 0x23, 0x71, 0xb2, 0x4e, 0xf8, 0x0d, 0xee, 0x7e, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x52, 0x26, 0xb2, 0xee, 0x9a, 0x01, 0x00, 0x00,
}
